#
# Config file generated by Abinit
#
# NOTE: You may adjust it before running 'configure'.
#

# Abinit paths
with_abinit_builddir="/media/witchariot/Grand_Tank/QMTIS/src/QM"
with_abinit_srcdir="/media/witchariot/Grand_Tank/QMTIS/src/QM"

# C support
CPP="gcc -E"
CPPFLAGS=""
CC="gcc"
CFLAGS=" -g -O2 -mtune=native -march=native  "
CC_LDFLAGS="    "

# C++ support
XPP=""
XPPFLAGS="    "
CXX="g++"
CXXFLAGS=" -g -O2 -mtune=native -march=native  "
CXX_LDFLAGS="    "

# Fortran support
FPP=""
FPPFLAGS="    "
FC="gfortran"
FCFLAGS=" -g -ffree-line-length-none   -O2 -mtune=native -march=native"
FC_LDFLAGS="    "
with_fc_vendor="gnu"
with_fc_version="4.8"

# Python support
PYTHON="python"
PYFLAGS=""
PYTHON_CPPFLAGS="-I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include"

# Utilities
AR="ar"
ARFLAGS="     rc"
RANLIB="ranlib"

# Parallel I/O use flags
lib_etsf_io_incs=""
lib_etsf_io_libs=""
lib_netcdf_incs=""
lib_netcdf_libs=""

# Linear algebra use flags
lib_linalg_fcflags=""
lib_linalg_ldflags=""
lib_linalg_incs="-I$(fallbacks_instdir)/include"
lib_linalg_libs="-L$(fallbacks_instdir)/lib -llapack -lblas"

# FFT use flags
lib_fft_incs=""
lib_fft_libs=""

# Feature triggers use flags
lib_bigdft_incs=""
lib_bigdft_libs=""
lib_gsl_incs="@lib_gsl_incs@"
lib_gsl_libs="@lib_gsl_libs@"
lib_levmar_incs="@lib_levmar_incs@"
lib_levmar_libs="@lib_levmar_libs@"
lib_libxc_incs=""
lib_libxc_libs=""
lib_papi_incs="@lib_papi_incs@"
lib_papi_libs="@lib_papi_libs@"
lib_triqs_incs=""
lib_triqs_libs=""
lib_wannier90_bins=""
lib_wannier90_incs=""
lib_wannier90_libs=""
lib_yaml_incs=""
lib_yaml_libs=""
